name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # or the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t elianrenteria/my_fast_api:latest --push .

    - name: SSH to Raspberry Pi and Redeploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 2222
        script: |
          docker pull elianrenteria/my_fast_api:latest
          docker stop myfastapi || true
          docker rm myfastapi || true
          docker run -d --network host --restart always --name myfastapi elianrenteria/my_fast_api:latest

